### ISSUE TITLE
Engineering track course to be completed

### ISSUE THREAD

**Issue by Adam-abu1** [Adam-abu1/Treehouse#2]
## TO-DO
*Course left to be completed for the engineering stream*

* [ ] Git Basics (Treehouse)
* [ ] Ruby Essential Training (Lynda)
* [ ] CSS Essential Training (Lynda)

👍 👨 ⭕️
